### PR TITLE
Master

### PR DESCRIPTION
**Pull request by mrpullen**
Resolve issue 10 

Should pull down latest install script, and run it. 

By allowing an additional parameter (SourceUrl) we can specify where to retrieve the install file from. This defaults to chocolatey standard install, but could be used to provide customized installs scripts, for environments without internet access, or for customized installers.

### CODE REVIEW

**Comment by lawrencegripper** [comment]
Thanks for the PR, like the idea of a customized script location for offline environments which might be using an internal nuget repo for the packages. Will have a look through this today.

**Comment by lawrencegripper** [comment]
Hi @mrpullen, sorry for the delay. Had a chance to have a quick look and initial pass all looks good. Just need to update the params on ChocoInstaller to allow the $SourceUrl to be optional. Ideally also changing the parameter name to be more description like "ChocoInstallScriptUrl" would be good too. 

Thanks again for the PR, look forward to the update and then can test again and merge.

**Comment by mrpullen** [comment]
Latest should resolve this. 

Thanks, my first contribution :)

**Comment by lawrencegripper** [comment]
np, thanks for helping out. 

Looks good, all merged now.

**Pull request merged**
