### PR TITLE
multiversion install and optimize choco install

### PR DESCRIPTION
**Pull request by wizarden1**
Fixes and changes:

- remove trailing spaces for newer version of test
- rebuild cChocoPackageInstall for multi version install
- rewrite cChocoInstaller for use nuget source(chocolate nuget source) directly
- add example how to use multiple version

### CODE REVIEW

**Comment by pauby** [comment]
@wizarden1 Can you break this PR into two separate ones - 'multiversion install' and 'optimize choco install'? Makes it easier to review.

Can I also ask you to create a feature branch and PR from that rather than your own development branch?

On first glance the code you've submitted doesn't adhere to the current code style - can I ask you to make sure it does?

**Comment by wizarden1** [comment]
> @wizarden1 Can you break this PR into two separate ones - 'multiversion install' and 'optimize choco install'? Makes it easier to review.

Yes. Sure, no problem.
 
> Can I also ask you to create a feature branch and PR from that rather than your own development branch?

Also, no problem.

> On first glance the code you've submitted doesn't adhere to the current code style - can I ask you to make sure it does?

How, and what do you mean?

**Comment by pauby** [comment]
> How, and what do you mean?

The two that jumped out on a quick glance over were if / else statements should not be on a single line and datatypes should be lowercase and don't need `System.` in them (ie. `System.String`). There will likely be others (I'm updating the contribution guidelines just now).

**Comment by wizarden1** [comment]
> 
> 
> > How, and what do you mean?
> 
> The two that jumped out on a quick glance over were if / else statements should not be on a single line and datatypes should be lowercase and don't need `System.` in them (ie. `System.String`). There will likely be others (I'm updating the contribution guidelines just now).

Ok, I'll recheck and fix. Thanks.

**Comment by pauby** [comment]
This has been superceded by #142 and #143 .

**Pull request closed without merging**
