### PR TITLE
cChocoPackageInstall Allow "Latest" as a package version #39

### PR DESCRIPTION
**Pull request by DamianBis**
issue #39

Have tested on Powershell 5.0 with Azure DSC.

### CODE REVIEW

**Comment by DamianBis** [comment]
@ebekker @lawrencegripper any chance we can get this merged in? I'm currently running a fork of the DSC resource so i can use this functionality.

**Comment by lawrencegripper** [comment]
Sorry Damian, I've added you as a collabor on the project as your contributions are great and I fear we're slowing you down!

**Comment by javydekoning** [comment]
@DamianBis this cannot be merged in. It will break functionality from newer commits. Also you should not manually increase the build-number, the AppVeyor will take care of that here: https://github.com/PowerShellOrg/cChoco/blob/master/AppVeyor/AppVeyorDeploy.ps1#L15.

**Comment by lawrencegripper** [comment]
Apologies, @DamianBis got confused between yourself and @javydekoning last night - meant to offer to @javydekoning. 

@javydekoning you offered to assist with the project a while back in an issue, are you still up for it? If your still keen I've added you as a collaborator. My first child is on the way at the moment so time is a bit tight!

**Comment by javydekoning** [comment]
@lawrencegripper sure, I'm still up for it. I'll start some work tomorrow. Congratulations on your upcoming baby!

@DamianBis are you willing to rewrite this based upon the latest Master branch? It's a very welcome addition and I would be happy to review/merge if it doesn't brake other features.

**Comment by lawrencegripper** [comment]
@javydekoning Thanks, she arrived on early this week and all going well. Also thanks for the hardwork, really good to see the project moving forward

**Comment by grest** [comment]
@DamianBis, any chance to merge it with the latest version?

**Comment by javydekoning** [comment]
Right so I've made some progress implementing this. I've also included some unit tests. If I have some more time this weekend I'll get this finished.

Have a look at: https://github.com/PowerShellOrg/cChoco/blob/development/DSCResources/cChocoPackageInstall/cChocoPackageInstall.psm1#L89-L91 

And: 
https://github.com/PowerShellOrg/cChoco/blob/development/DSCResources/cChocoPackageInstall/cChocoPackageInstall.psm1#L287-L301

And:
https://github.com/PowerShellOrg/cChoco/blob/development/DSCResources/cChocoPackageInstall/cChocoPackageInstall.psm1#L324-L356

**Comment by javydekoning** [comment]
The resource now has a autoupgrade boolean available for use, hence we are now closing this PR.

**Pull request closed without merging**
