### PR TITLE
Added support for Command Line parameter to Choco

### PR DESCRIPTION
**Pull request by alkampfergit**
Related to my issue [https://github.com/PowerShellOrg/cChoco/issues/12](https://github.com/PowerShellOrg/cChoco/issues/)
I need to be able to pass specific choco parameters to choco, Ex: --allow-downgrade.

To accomplish this need I added a CmdParams parameter to the original package.

I'm not a DSC expert, so feel free to reject the pull request if it is not correct.

### CODE REVIEW

**Comment by lawrencegripper** [comment]
Sorry I missed this PR while I was on holiday. Will take a look and test it out later this week and hopefully merge in. Thanks for the submission!

**Comment by alkampfergit** [comment]
No problem, thanks.

**Comment by lawrencegripper** [comment]
Hey, all looks good. Would you be alright to rename the CmdParams argument to something like AdditionalChocoArguments? Might just be me but it gets a bit funny distinguishing between that and the existing package Params variable.

**Comment by lawrencegripper** [comment]
Ps. Thanks for also updating the examples doc, great for others to see how this can be used.

**Comment by alkampfergit** [comment]
Ok for the rename into AdditionalChocoArguments, probably it is more clear
for the reader the purpose of the parameter.

Thanks :).

Bye.

## 

Gian Maria Ricci
Cell: +39 320 0136949

http://mvp.microsoft.com/en-us/mvp/Gian%20Maria%20Ricci-4025635
http://www.linkedin.com/in/gianmariaricci  https://twitter.com/alkampfer
  http://feeds.feedburner.com/AlkampferEng

**Comment by lawrencegripper** [comment]
Hi @alkampfergit you still OK to do do the rename so I can merge?

**Comment by alkampfergit** [comment]
Sorry that I've completely forgot this issue, this evening I'll do the
rename.

## 

Gian Maria Ricci
Cell: +39 320 0136949

http://mvp.microsoft.com/en-us/mvp/Gian%20Maria%20Ricci-4025635
http://www.linkedin.com/in/gianmariaricci  https://twitter.com/alkampfer
  http://feeds.feedburner.com/AlkampferEng

**Comment by ebekker** [comment]
@alkampfergit, it seems this PR has deviated a bit from `master`.

I'm going to close this PR out for now.  If you still wish to contribute it in, please update it with the latest from `master` and resubmit, thanks.

**Comment by alkampfergit** [comment]
Perfect,

I must admit that I still use the old version with no problem and had a
little time to fix this pull request. If I'll have time I'll rebase onto
new master and resubmit the request.

Thanks.

## 

Gian Maria Ricci
Cell: +39 320 0136949

http://mvp.microsoft.com/en-us/mvp/Gian%20Maria%20Ricci-4025635
http://www.linkedin.com/in/gianmariaricci  https://twitter.com/alkampfer
  http://feeds.feedburner.com/AlkampferEng

**Pull request closed without merging**
